# Generated by Django 3.0.3 on 2020-05-14 08:53

import authentication.models
from django.db import migrations, models
import django.db.models.deletion
import recordOfficer.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_registeredby'),
        ('recordOfficer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new',
        ),
        migrations.RemoveField(
            model_name='incomingletters',
            name='lastEditBy',
        ),
        migrations.RemoveField(
            model_name='incomingmemos',
            name='lastEditBy',
        ),
        migrations.RemoveField(
            model_name='outgoingletters',
            name='lastEditBy',
        ),
        migrations.RemoveField(
            model_name='outgoingmemos',
            name='lastEditBy',
        ),
        migrations.AddField(
            model_name='incomingletters',
            name='forwardedTo',
            field=models.CharField(default='Director', max_length=200, verbose_name='Forwarded To'),
        ),
        migrations.AlterField(
            model_name='incomingletters',
            name='author',
            field=models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='incomingletters',
            name='directorate',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='authentication.Directorates', verbose_name='Directorate'),
        ),
        migrations.AlterField(
            model_name='incomingletters',
            name='file',
            field=models.FileField(upload_to='incoming_documents/', validators=[recordOfficer.models.validate_file], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='incomingmemos',
            name='author',
            field=models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='incomingmemos',
            name='file',
            field=models.FileField(upload_to='incoming_documents/', validators=[recordOfficer.models.validate_file], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='incomingmemos',
            name='receivedFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Directorates', verbose_name='Received From'),
        ),
        migrations.AlterField(
            model_name='outgoingletters',
            name='author',
            field=models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='outgoingletters',
            name='directorate',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='authentication.Directorates', verbose_name='Directorate'),
        ),
        migrations.AlterField(
            model_name='outgoingletters',
            name='file',
            field=models.FileField(upload_to='outgoing_documents/', validators=[recordOfficer.models.validate_file], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='outgoingmemos',
            name='author',
            field=models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='outgoingmemos',
            name='file',
            field=models.FileField(upload_to='outgoing_documents/', validators=[recordOfficer.models.validate_file], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='outgoingmemos',
            name='sentTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Directorates', verbose_name='Sent To'),
        ),
        migrations.DeleteModel(
            name='Directorates',
        ),
    ]
