# Generated by Django 3.0.3 on 2020-05-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0002_auto_20200514_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingletters',
            name='forwardedTo',
            field=models.CharField(default='Director', max_length=200, verbose_name='Forwarded To'),
        ),
    ]
