# Generated by Django 3.0.3 on 2020-05-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0003_outgoingletters_forwardedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmemos',
            name='forwardedTo',
            field=models.CharField(default='Director', max_length=200, verbose_name='Forwarded To'),
        ),
        migrations.AddField(
            model_name='outgoingmemos',
            name='forwardedTo',
            field=models.CharField(default='Director', max_length=200, verbose_name='Forwarded To'),
        ),
    ]
