# Generated by Django 3.0.3 on 2020-06-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0004_auto_20200519_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingletters',
            name='byDirector',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Director'),
        ),
        migrations.AddField(
            model_name='incomingletters',
            name='byTeamleader',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Team Leader'),
        ),
        migrations.AddField(
            model_name='incomingletters',
            name='byleadengineer',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Lead Engineer'),
        ),
        migrations.AddField(
            model_name='incomingletters',
            name='byprojectengineer',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Project Engineer'),
        ),
    ]
