# Generated by Django 3.0.3 on 2020-07-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_auto_20200718_1220'),
        ('recordOfficer', '0005_auto_20200622_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingletters',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.Projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='incomingmemos',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.Projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='outgoingletters',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.Projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='outgoingmemos',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.Projects', verbose_name='Project'),
        ),
    ]
