# Generated by Django 3.0.3 on 2020-07-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0006_auto_20200718_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingletters',
            name='lastEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Edit'),
        ),
        migrations.AlterField(
            model_name='incomingmemos',
            name='lastEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Edit'),
        ),
        migrations.AlterField(
            model_name='outgoingletters',
            name='lastEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Edit'),
        ),
        migrations.AlterField(
            model_name='outgoingmemos',
            name='lastEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Edit'),
        ),
    ]
