# Generated by Django 3.0.3 on 2020-07-26 09:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0007_auto_20200720_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorsLetterMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTo', models.CharField(default='Director', max_length=200, verbose_name='Message To')),
                ('message', models.CharField(default='Director', max_length=200, verbose_name='Message')),
                ('dateForwarded', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Forwarded')),
                ('referenceNumber', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.IncomingLetters', verbose_name='Reference Number')),
            ],
        ),
        migrations.DeleteModel(
            name='Projects',
        ),
    ]
