# Generated by Django 3.0.3 on 2020-07-26 12:14

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0008_auto_20200726_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorslettermessages',
            options={'verbose_name_plural': 'Directors Letter Messages'},
        ),
        migrations.AddField(
            model_name='directorslettermessages',
            name='author',
            field=models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='directorslettermessages',
            name='message',
            field=models.TextField(default='No Message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='directorslettermessages',
            name='messageTo',
            field=models.CharField(default='Team Leader', max_length=200, verbose_name='Message To'),
        ),
    ]
