# Generated by Django 3.0.3 on 2020-07-26 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0009_auto_20200726_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorslettermessages',
            name='dateForwarded',
        ),
        migrations.AddField(
            model_name='directorslettermessages',
            name='dateSent',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent'),
        ),
    ]
