# Generated by Django 3.0.3 on 2020-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0011_directorslettermessagesout_directorsmemomessages_directorsmemomessagesout'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingletters',
            name='byDirector',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Director'),
        ),
        migrations.AddField(
            model_name='outgoingletters',
            name='byTeamleader',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Team Leader'),
        ),
        migrations.AddField(
            model_name='outgoingletters',
            name='byleadengineer',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Lead Engineer'),
        ),
        migrations.AddField(
            model_name='outgoingletters',
            name='byprojectengineer',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Project Engineer'),
        ),
    ]
