# Generated by Django 3.0.3 on 2020-08-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0012_auto_20200823_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmemos',
            name='byDirector',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Director'),
        ),
        migrations.AddField(
            model_name='incomingmemos',
            name='byTeamleader',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Team Leader'),
        ),
        migrations.AddField(
            model_name='incomingmemos',
            name='byleadengineer',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Lead Engineer'),
        ),
        migrations.AddField(
            model_name='incomingmemos',
            name='byprojectengineer',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Project Engineer'),
        ),
        migrations.AddField(
            model_name='outgoingmemos',
            name='byDirector',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Director'),
        ),
        migrations.AddField(
            model_name='outgoingmemos',
            name='byTeamleader',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Team Leader'),
        ),
        migrations.AddField(
            model_name='outgoingmemos',
            name='byleadengineer',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Lead Engineer'),
        ),
        migrations.AddField(
            model_name='outgoingmemos',
            name='byprojectengineer',
            field=models.CharField(default='no', max_length=200, null=True, verbose_name='Seen by Project Engineer'),
        ),
        migrations.AlterField(
            model_name='directorslettermessages',
            name='message',
            field=models.TextField(default='Message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='directorslettermessagesout',
            name='message',
            field=models.TextField(default='Message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='directorsmemomessages',
            name='message',
            field=models.TextField(default='Message', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='directorsmemomessagesout',
            name='message',
            field=models.TextField(default='Message', verbose_name='Message'),
        ),
    ]
