# Generated by Django 3.0.3 on 2020-08-23 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0013_auto_20200823_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorsmemomessagesout',
            name='subject',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.OutgoingMemos', verbose_name='Subject'),
        ),
    ]
