# Generated by Django 3.0.3 on 2020-10-15 11:02

import authentication.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recordOfficer', '0017_auto_20201014_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEngineersMemoMessagesOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTo', models.CharField(default='Lead Engineer', max_length=200, verbose_name='Message To')),
                ('message', models.TextField(default='Message', verbose_name='Message')),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('author', models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author')),
                ('subject', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.OutgoingMemos', verbose_name='Subject')),
            ],
            options={
                'verbose_name_plural': 'Project Engineers Memo Messages Out',
            },
        ),
        migrations.CreateModel(
            name='ProjectEngineersMemoMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTo', models.CharField(default='Lead Engineer', max_length=200, verbose_name='Message To')),
                ('message', models.TextField(default='Message', verbose_name='Message')),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('author', models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author')),
                ('subject', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.IncomingMemos', verbose_name='Subject')),
            ],
            options={
                'verbose_name_plural': 'Project Engineers Memo Messages',
            },
        ),
        migrations.CreateModel(
            name='ProjectEngineersLetterMessagesOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTo', models.CharField(default='Lead Engineer', max_length=200, verbose_name='Message To')),
                ('message', models.TextField(default='Message', verbose_name='Message')),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('author', models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author')),
                ('referenceNumber', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.OutgoingLetters', verbose_name='Reference Number')),
            ],
            options={
                'verbose_name_plural': 'Project Engineers Letter Messages Out',
            },
        ),
        migrations.CreateModel(
            name='ProjectEngineersLetterMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTo', models.CharField(default='Lead Engineer', max_length=200, verbose_name='Message To')),
                ('message', models.TextField(default='Message', verbose_name='Message')),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('author', models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author')),
                ('referenceNumber', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.IncomingLetters', verbose_name='Reference Number')),
            ],
            options={
                'verbose_name_plural': 'Project Engineer Letter Messages',
            },
        ),
        migrations.CreateModel(
            name='LeadEngineersMemoMessagesOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTo', models.CharField(default='Project Engineer', max_length=200, verbose_name='Message To')),
                ('message', models.TextField(default='Message', verbose_name='Message')),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('author', models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author')),
                ('subject', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.OutgoingMemos', verbose_name='Subject')),
            ],
            options={
                'verbose_name_plural': 'Lead Engineers Memo Messages Out',
            },
        ),
        migrations.CreateModel(
            name='LeadEngineersMemoMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTo', models.CharField(default='Project Engineer', max_length=200, verbose_name='Message To')),
                ('message', models.TextField(default='Message', verbose_name='Message')),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('author', models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author')),
                ('subject', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.IncomingMemos', verbose_name='Subject')),
            ],
            options={
                'verbose_name_plural': 'Lead Engineers Memo Messages',
            },
        ),
        migrations.CreateModel(
            name='LeadEngineersLetterMessagesOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTo', models.CharField(default='Project Engineer', max_length=200, verbose_name='Message To')),
                ('message', models.TextField(default='Message', verbose_name='Message')),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('author', models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author')),
                ('referenceNumber', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.OutgoingLetters', verbose_name='Reference Number')),
            ],
            options={
                'verbose_name_plural': 'Lead Engineers Letter Messages Out',
            },
        ),
        migrations.CreateModel(
            name='LeadEngineersLetterMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageTo', models.CharField(default='Project Engineer', max_length=200, verbose_name='Message To')),
                ('message', models.TextField(default='Message', verbose_name='Message')),
                ('dateSent', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Sent')),
                ('author', models.CharField(default=authentication.models.User, max_length=400, verbose_name='Author')),
                ('referenceNumber', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='recordOfficer.IncomingLetters', verbose_name='Reference Number')),
            ],
            options={
                'verbose_name_plural': 'Lead Engineers Letter Messages',
            },
        ),
    ]
