# Generated by Django 3.0.3 on 2020-07-18 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20200528_1219'),
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='directorate',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Directorates', verbose_name='Directorate'),
        ),
    ]
