# Generated by Django 3.0.3 on 2020-07-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20200528_1219'),
        ('director', '0002_auto_20200718_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='lastEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Edit'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='author',
            field=models.CharField(max_length=400, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='directorate',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='authentication.Directorates', verbose_name='Directorate'),
        ),
    ]
