# Generated by Django 3.0.3 on 2020-07-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_auto_20200720_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='lastEdit',
        ),
    ]
