# Generated by Django 3.0.3 on 2020-07-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_remove_projects_lastedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='lastEdit',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Edit'),
        ),
    ]
