# Generated by Django 3.0.3 on 2020-08-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_user_gender'),
        ('director', '0006_auto_20200726_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='assignedToLE',
            field=models.CharField(default='Lead Engineer', max_length=200, verbose_name='Project Assigned To Lead Engineer'),
        ),
        migrations.AddField(
            model_name='projects',
            name='assignedToPE',
            field=models.CharField(default='Project Engineer', max_length=200, verbose_name='Project Assigned To Project Engineer'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='assignedTo',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='authentication.Teams', verbose_name='Project Assigned To Team'),
        ),
    ]
