# Generated by Django 3.0.3 on 2020-09-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0009_auto_20200924_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projectName',
            field=models.TextField(max_length=500, verbose_name='Project Name'),
        ),
    ]
