# Generated by Django 3.0.3 on 2020-04-12 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directorates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorate', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Directorates',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=500, unique=True, verbose_name='Badge Number')),
                ('firstName', models.CharField(blank=True, max_length=500, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=500, verbose_name='Middel Name')),
                ('lastName', models.CharField(blank=True, max_length=500, verbose_name='Last Name')),
                ('email', models.CharField(max_length=500, unique=True, verbose_name='Email')),
                ('phoneNumber', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format : 09******** or +2519******** up to 15 digits allowed', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone Number')),
                ('title', models.CharField(blank=True, choices=[('Director', 'Director'), ('Team Leader', 'Team Leader'), ('Office Assistant', 'Office Assistant'), ('Lead Engineer', 'Lead Engineer'), ('Record Officer', 'Record Officer'), ('Project Engineer', 'Project Engineer'), ('Secretary', 'Secretary'), ('HR Personnel', 'HR Personnel')], max_length=100, verbose_name='Title')),
                ('emergencyContactName', models.CharField(blank=True, max_length=500, verbose_name='Emergency Contact Name')),
                ('emergencyContactPhone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format : 09******** or +2519******** up to 15 digits allowed', regex='^\\+?1?\\d{10,15}$')], verbose_name='Emergency Contact Phone')),
                ('profilePicture', models.ImageField(blank=True, default='default.png', upload_to='Profile_Pictures/')),
                ('lastEdit', models.DateTimeField(auto_now=True, verbose_name='Last Edit')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('directorate', models.ForeignKey(blank=True, default=1, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Directorates', verbose_name='Directorate')),
                ('team', models.ForeignKey(blank=True, default=1, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Teams', verbose_name='Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
