# Generated by Django 3.0.3 on 2020-04-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Director', 'Director'), ('Team Leader', 'Team Leader'), ('Office Assistant', 'Office Assistant'), ('Lead Engineer', 'Lead Engineer'), ('Record Officer', 'Record Officer'), ('Project Engineer', 'Project Engineer'), ('Secretary', 'Secretary'), ('HR Officer', 'HR Officer')], max_length=100, verbose_name='Title'),
        ),
    ]
