# Generated by Django 3.0.3 on 2020-04-20 10:19

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200420_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registeredBy',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=400, verbose_name='Registered By'),
        ),
    ]
