# Generated by Django 3.0.3 on 2020-04-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_registeredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registeredBy',
            field=models.CharField(blank=True, default='Admin', max_length=400, verbose_name='Registered By'),
        ),
    ]
