# Generated by Django 3.0.3 on 2020-04-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200420_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registeredBy',
        ),
    ]
