# Generated by Django 3.0.3 on 2020-05-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_registeredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='Profile_Pictures/default.png', upload_to='Profile_Pictures/', verbose_name='Profile Picture'),
        ),
    ]
