# Generated by Django 3.0.3 on 2020-05-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200508_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registeredBy',
            field=models.CharField(blank=True, default='Admin', max_length=400, verbose_name='Registered By'),
        ),
    ]
