# Generated by Django 3.0.3 on 2020-05-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_registeredby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registeredBy',
        ),
    ]
