# Generated by Django 3.0.3 on 2020-05-28 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_user_registeredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emergencyContactPhone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter your phonenumber in the format starting with: 09 or +251', regex='^\\+?1?\\d{10,15}$')], verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter your phonenumber in the format starting with: 09 or +251', regex='^\\+?1?\\d{10,15}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='Profile_Pictures/default.png', null=True, upload_to='Profile_Pictures/', verbose_name='Profile Picture'),
        ),
    ]
